### ISSUE TITLE
Schema Migration Tracking & Verification

### ISSUE THREAD

**Issue by blowdart** [aspnet/Identity#1254]
- [ ] Test migrations from 1.1 schema.

- [ ]  Check interop with database sharing from a 1.0/1.1 app.

- [x]  Ensure it's opt-in for existing code, and opt-in automatically for File -> New Project

- [ ]  Document how to create change scripts

- [ ]  Test how VS Publish would apply migrations to azure, and document

**Comment by Eilon** [comment]
Any further work planned in 2.1.0-preview2?

**Comment by Eilon** [comment]
@ajcvickers / @blowdart - move to RC1/RTM? Or 2.2.0?

**Comment by ajcvickers** [comment]
@Eilon It would be good to test this as part of preview2 validation, but if @HaoK can't fit it in then I'm okay punting to RC1. I'll sync up with @HaoK tomorrow.

**Comment by Eilon** [comment]
Not trying to push either way, just reminding that time is running out 😄

**Comment by blowdart** [comment]
RC1, definitely can't be pushed to 2.2 as it's checking 2.1 functions :p

**Comment by ajcvickers** [comment]
Closing this for now since these changes have long since shipped.
